# Generated by Django 3.2.16 on 2023-01-24 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0002_auto_20230124_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommedBox',
            new_name='RecommendBox',
        ),
    ]
